from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, Float, Boolean, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from app.database import Base


class Product(Base):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    artisan_id = Column(Integer, ForeignKey("artisan_profiles.id"), nullable=False, index=True)
    title = Column(String, index=True, nullable=False)
    description = Column(Text, nullable=False)
    price = Column(Float, nullable=False)
    craft_type = Column(String, index=True, nullable=False)
    materials = Column(String, nullable=True)  # Comma-separated or descriptive string
    dimensions = Column(String, nullable=True)  # e.g., "12x8x6 cm"
    weight_grams = Column(Float, nullable=True)
    production_time_days = Column(Integer, default=3)
    stock_quantity = Column(Integer, default=1)
    image_url = Column(String, nullable=True)
    ai_tags = Column(String, nullable=True)  # Comma-separated smart tags generated by AI
    ai_suggested_price = Column(Float, nullable=True)
    is_available = Column(Boolean, default=True)
    views_count = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    artisan = relationship("ArtisanProfile", back_populates="products")
    linkages = relationship("MarketLinkage", back_populates="product", cascade="all, delete-orphan")
